import type { Metadata } from "next";
import "./globals.css";
import { HeroUIProvider } from "@heroui/system";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import Header from "@/views/layout/Header";
import Main from "@/views/layout/Main";
import { SITE_NAME } from "@/configs/info";

export const metadata: Metadata = {
  title: `${SITE_NAME} - Welcome!`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <HeroUIProvider>
          <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            <div className="relative flex min-h-screen flex-col">
              <Header></Header>
              <Main>{children}</Main>
            </div>
          </NextThemesProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}
